### ISSUE TITLE
Refactor Plasma Gun

### ISSUE THREAD

**Issue by gyahu** [PaperTanuki/mochadoom#11]
Change Plasma Gun to Holy Water

**Comment by cdotte** [comment]
- MF estan definidos en: gamelogic/mobj_t.java
- Acciones del tipo A_something estan en: gamelogic/ActionFunction.java (class A_FirePlasma)
- MT estan definidos en: data/info.java (MT_PLASMA {la bala del plasmagun})
  -MT_MISC28 coresponde a: "PlasmaGun"(?)

**Comment by cdotte** [comment]
Changed all features of plasmagun to behave a like holy water weapon
