### ISSUE TITLE
Implement Hybrid Class

### ISSUE THREAD

**Issue by gyahu** [PaperTanuki/mochadoom#12]
Add Hybrid Class that inherit form Monster Class

**Comment by diegodi** [comment]
Add inmunity parameter for daylight damage and silver bullet damage.

**Comment by diegodi** [comment]
Silver bullet immunity added

**Comment by diegodi** [comment]
Class has been implemented, however, just like with the vampire class, damage by daylight (or immunity in this case) was not added.
