### ISSUE TITLE
Include Cheatcodes

### ISSUE THREAD

**Issue by gyahu** [PaperTanuki/mochadoom#13]
Add Flags for the Campire and Werewolf cheatcodes.

**Comment by rodrigo-hp** [comment]
Inside the statusbar package, in the StatusBar class there are a lot of variables defining the cheat codes. These are sequences of numbers (possibly referencing to the buttons of the keyboard that have to be pressed for activating the cheatcode). Search for "behold" on the code.

**Comment by diegodi** [comment]
Logic behind cheatcodes has been implemented, however, due to the way the game manages everything as a _mobj_ type, it was not possible to change the attributes of the player because of a conflict between the player object and the monster object.
