### ISSUE TITLE
Add Moon Phases

### ISSUE THREAD

**Issue by rodrigo-hp** [PaperTanuki/mochadoom#19]
Depending on the moon phase, werewolves become stronger or weaker. Full Moon means maximum power and New Moon means minimum power.

**Comment by diegodi** [comment]
Moon phases have been implemented and the speed of monsters is affected by it, but the power is still the same on all moon phases.

**Comment by pudumagico** [comment]
Should we close the issue? the power of the monster is not controlled by the class.

**Comment by diegodi** [comment]
Correct, power of monsters isn't controlled by this class.
