### ISSUE TITLE
Implement Werewolf Class

### ISSUE THREAD

**Issue by rodrigo-hp** [PaperTanuki/mochadoom#6]
RS0006: Implement Werewolf Class
Description : Add the Werewolf class that inherit from Monster
Source : Teacher

**Comment by rodrigo-hp** [comment]
Include weakness parameter.

**Comment by diegodi** [comment]
Change appearance of werewolf during day to normal monster appearance.
Include strength change according to moon phase.

**Comment by diegodi** [comment]
Change of sprite during times of day has been added, strength change was not added.
