### ISSUE TITLE
Implement Vampire Class

### ISSUE THREAD

**Issue by rodrigo-hp** [PaperTanuki/mochadoom#8]
Add Vampire class that Inherit from Monster

**Comment by diegodi** [comment]
Include weakness parameter for holy water.
Include damage when exposed to daylight.
Include hp regeneration parameter.
Summon bats when weak, not only when dying

**Comment by diegodi** [comment]
Health regeneration and bat summoning done.

**Comment by diegodi** [comment]
Weakness to holy water added. Damage by sunlight could not be implemented.
