### ISSUE TITLE
Implement Ghoul Class

### ISSUE THREAD

**Issue by rodrigo-hp** [PaperTanuki/mochadoom#9]
Add Ghoul Class that inherit form Monster Class

**Comment by diegodi** [comment]
Add logic so that ghoul can eat dead monsters to regenerate health.
Add resistance to regular weapons, but less than vampire.

**Comment by diegodi** [comment]
Resistance added.

**Comment by diegodi** [comment]
Ghouls regenerate hp when attacking other monsters, however, they don't eat corpses to regenerate health.
